steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sadproject2025/curebot', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sadproject2025/curebot']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - curebot
      - --image=gcr.io/sadproject2025/curebot
      - --region=us-central1
      - --platform=managed
      
